# Generated by Django 5.0.6 on 2024-07-04 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_mascota_subtipo_alter_mascota_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='subtipo',
            field=models.CharField(choices=[('Otro', 'Otro'), ('Gato', [('Volador', 'Volador'), ('Nian', 'Nian')]), ('Reptil', [('Lagarto', 'Lagarto'), ('Anaconda', 'Anaconda')]), ('PERRO', [('Chico', 'Chico'), ('Grande', 'Grande'), ('Verde', 'Verde')])], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('OTRO', 'Otro'), ('REPTIL', 'Reptil'), ('GATO', 'Gato')], max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='celular',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
