# Generated by Django 5.0.6 on 2024-07-04 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_mascota_subtipo_alter_mascota_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mascota',
            name='subtipo',
            field=models.CharField(choices=[('Reptil', [('Lagarto', 'Lagarto'), ('Anaconda', 'Anaconda')]), ('PERRO', [('Chico', 'Chico'), ('Grande', 'Grande'), ('Verde', 'Verde')]), ('Otro', 'Otro'), ('Gato', [('Volador', 'Volador'), ('Nian', 'Nian')])], default='Otro', max_length=20),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='tipo',
            field=models.CharField(choices=[('PERRO', 'Perro'), ('REPTIL', 'Reptil'), ('OTRO', 'Otro'), ('GATO', 'Gato')], max_length=15),
        ),
    ]
