# Generated by Django 5.0.6 on 2024-07-04 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_mascota_subtipo_alter_mascota_tipo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Mascota',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
